train_django/products/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
# from django.views.decorators.cache import cache_page

from products.views import (ProductsListView, basket_add_item,
                            basket_delete_items, basket_delete_one_item)

TIMEOUT = 30
app_name = 'products'

urlpatterns = [
    # path('', cache_page(TIMEOUT)(ProductsListView.as_view()), name='index'),
    path('', ProductsListView.as_view(), name='index'),
    path('<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('page/<int:page>/', ProductsListView.as_view(), name='page'),
    path('basket-add-item/<int:product_id>/', basket_add_item, name='basket_add_item'),
    path('basket-delete-items/<int:id>/', basket_delete_items, name='basket_delete_items'),
    path('basket-delete-one-item/<int:product_id>/', basket_delete_one_item, name='basket_delete_one_item'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

train_django/train_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# пишем импорт относительно manage.py, поэтому не ..products
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    # path('test-context/', test_context, name='test_context'),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

train_django/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(next_page='index'), name='login'),
    path('signup/', UserRegistrationView.as_view(), name='signup'),
    # UpdateView всегда работает с конкретным объектом, передаём PrimaryKey (UserID)
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('verify/<str:username>/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='verify'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

train_django/products/models.py
from django.db import models

from users.models import User

# модели = таблицы


class ProductCategory(models.Model):
    name: str = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name: str = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True)
    short_description: str = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} | {self.category} | '


class BasketItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    modified_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Basket item of {self.user.username} | Product "{self.product}" ({self.quantity})'

    # можно вызывать ТОЛЬКО методы без аргументов
    def sum(self):
        return self.quantity * self.product.price

train_django/products/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect
# from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.core.cache import cache

from common.views import TitleMixin
from products.models import BasketItem, Product, ProductCategory

# from django.core.paginator import Paginator

# Create your views here.


class IndexView(TitleMixin, TemplateView):
    template_name = 'products/index.html'
    title = 'Store'


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 3
    title = 'Store - Products'

    def get_queryset(self, **kwargs):
        queryset = super(ProductsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')

        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        categories = cache.get('categories')
        if not categories:
            timeout = 30
            context['categories'] = ProductCategory.objects.all()
            cache.set('categories', context['categories'], timeout)
        else:
            context['categories'] = categories
        return context


# не переводим в класс, т.к. это избыточно: слишком много надо переопределять
@login_required
def basket_add_item(request, product_id):
    user = request.user
    current_page = HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    product = Product.objects.get(id=product_id)
    basket_items = BasketItem.objects.filter(user=user, product=product)

    if not basket_items.exists():
        BasketItem.objects.create(user=user, product=product, quantity=1)
        return current_page
    else:
        basket_item = basket_items.first()
        basket_item.quantity += 1
        basket_item.save()
        return current_page


@login_required
def basket_delete_items(request, id):
    # user = request.user
    current_page = HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    basket_item = BasketItem.objects.get(id=id)
    basket_item.delete()
    return current_page


@login_required
def basket_delete_one_item(request, product_id):
    user = request.user
    current_page = HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    product = Product.objects.get(id=product_id)
    basket_items = BasketItem.objects.filter(user=user, product=product)

    if not basket_items.exists():
        # BasketItem.objects.create(user=user, product=product, quantity=1)
        messages.error(request, "Item doesn't exist")
        print(messages)
        return current_page
    else:
        basket_item = basket_items.first()
        if basket_item.quantity == 1:
            basket_item.delete()
        else:
            basket_item.quantity -= 1
            basket_item.save()
        return current_page

# def index(request):
#     context = {
#         'title': 'Store'
#     }
#     return render(request, 'products/index.html', context)


# def products(request, category_id=None, page=1):
#     context = {
#         'title': 'Products',
#         'categories': ProductCategory.objects.all(),
#     }
#
#     if category_id:
#         current_products = Product.objects.filter(category_id=category_id)
#     else:
#         current_products = Product.objects.all()
#
#     paginator = Paginator(current_products, 3)
#     products_paginator = paginator.page(page)
#     context.update({'products': products_paginator})
#
#     return render(request, 'products/products.html', context)


# def test_context(request):
#     context = {
#         'title': 'Test',
#         'header': 'Welcome!',
#         'username': 'John Doe',
#         'products': [
#             {'name': "Product1", 'price': 100500.0},
#             {'name': "Product2", 'price': 100600.0},
#             {'name': "Product3", 'price': 100700.0},
#         ],
#         # 'promotion': True,
#         'promoted_products': [
#             # {'name': "Promo1", 'old_price': 100500.0, 'price': 100400},
#             # {'name': "Promo2", 'old_price': 100500.0, 'price': 100400},
#         ]
#     }
#     return render(request, 'products/test-context.html', context)

train_django/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' user.id %}">{{ user.username }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js'%}" crossorigin="anonymous"></script>

</body>

</html>

train_django/products/templates/products/basket.html
{% if basket_items %}
    <div class="col-lg-5">
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Basket <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
        </h4>
        {% for item in basket_items %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ item.product.name }}</h5>
                    <p class="card-text">{{ item.product.short_description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">
                        <span class="text-muted">{{ item.quantity }} pc.</span>
{#                        можно вызывать ТОЛЬКО методы без аргументов #}
                        <span class="text-muted">{{ item.sum }} $</span>
                        <span class="text-muted">
                            <a href="{% url 'products:basket_add_item' item.product.id %}" style="text-decoration: none; color: gray;">
                                <i class="fas fa-cart-plus"></i>
                            </a>
                            <a href="{% url 'products:basket_delete_one_item' item.product.id %}" style="text-decoration: none; color: gray;">
                                <i class="fas fa-cart-arrow-down"></i>
                            </a>
                            <a href="{% url 'products:basket_delete_items' item.id %}" style="text-decoration: none; color: gray;">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
        {% endfor %}

        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Total</p>
                <h4 class="float-right">{{ total_sum }} $</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right">Purchase</button>
    </div>
{% else %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between mb-3">
        Basket is empty
    </h4>
{% endif %}

train_django/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">Store</h1>
                    <p>
                        Новые образы и лучшие бренды Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

train_django/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static cache %}

{% block css %}
    <link href="{% static 'css/products.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">Store</h1>
                <div class="list-group">
                    <a href="{% url 'products:index'%}"
                       class="list-group-item">
                        All items
                    </a>
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id%}"
                           class="list-group-item">
                            {{ category.name }}
                        </a>
                    {% endfor %}

                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg'%}" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg'%}" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg'%}" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

            {% if object_list %}
                <div class="row">
                {% cache 30 object_list %}
                    {% for product in object_list %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top"
                                     src="/media/{{ product.image }}"
                                     alt="">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#">{{ product.name }}</a>
                                </h4>
                                <h5>{{ product.price }} руб.</h5>
                                <p class="card-text">{{ product.short_description }}</p>
                            </div>
                            <div class="card-footer text-center">
                                <a href="{% url 'products:basket_add_item' product.id %}">
                                    <button type="button" class="btn btn-outline-success">
                                        Add to card
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                {% endcache %}
                </div>

                {% if is_paginated %}
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if page_obj.has_previous %} {% url 'products:page' page_obj.previous_page_number %} {% endif %}"
                               tabindex="-1" aria-disabled="true">
                                Previous
                            </a>
                        </li>
                        {% for page in paginator.page_range %}
                        <li class="page-item"><a class="page-link" href="{% url 'products:page' page %}">{{ page }}</a></li>
                        {% endfor %}
                        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if page_obj.has_next %} {% url 'products:page' page_obj.next_page_number %} {% endif %}">
                                Next
                            </a>
                        </li>
                    </ul>
                </nav>
                {% endif %}
            {% else %}
                <div class="container">
                    <h1 class="my-4 text-center">No items in this category yet</h1>
                </div>
            {% endif %}
            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Store 2021</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

train_django/products/templates/products/test-context.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ header }}</h1>
    <p>{{ username }}</p>
    {% for product in products %}
        <h3>{{ product.name }}</h3>
        <p>{{ product.price }} $</p>
    {% endfor %}

    {% if promoted_products %}
        <h2 style="color: red"><b>Sale!</b></h2>
        {% for product in promoted_products %}
            <h3>{{ product.name }}</h3>
            <p><s>{{ product.old_price }} $</s></p>
            <p>{{ product.price }} $</p>
        {% endfor %}
    {% endif %}
</body>
</html>